### ISSUE TITLE
Add ability to specify which C/C++ libraries to link against.

### ISSUE THREAD

**Issue by mbebenita** [wasdk/wasmexplorer-service#2]
```
#include <stdio.h>

int main() { 
  printf("Hello World");
  return 0;
}
```
I'm not sure what's going on but I'd expect this to pull in lots of dependencies, and it simply tries to import `printf`. See https://wasdk.github.io/WasmFiddle/?pobhj

**Comment by yurydelendik** [comment]
Since we are not linking, it pulls everything header has https://github.com/wasdk/wasmexplorer-service/blob/c31c6b34a8d3f1b3c81ce21d5931a913aca273f7/misc/include/libc/stdio.h#L102 . The implementation of import is in libc.

**Comment by mbebenita** [comment]
I see, so what's the linking story? For example, what I was trying to accomplish was to create a module that just implements `printf`and only `printf`. I was expecting to get a WebAssembly module that had most of printf implemented with some number of imported functions which I was going to implement in JS. I was then going to reduce the WebAssembly module to a minimum by removing WebAssembly functions to find some kind of a sweet spot.

**Comment by mbebenita** [comment]
This is a linker issue, and I've updated the title of the issue to reflect that.

**Comment by mbebenita** [comment]
From the IRC channel discussion. This is likely to produce large amounts of WebAssembly code that won't run out of the box, but I feel it's still important as an option to experiment with. We can turn it off by default.

**Comment by yurydelendik** [comment]
The server has "build" action which uses most recent llvm (clang + lld) and contains musl and libc++  libraries. See https://github.com/yurydelendik/wasmception

**Comment by yurydelendik** [comment]
Closing as resolved by using "build" action and using new clang and sysroot provided by wasmception.
